# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e64351efc11a74e1d18561b0aaa64a117e84b89d95e8383240801d170f56eb71bcf67093f0e49bab473a3fc2437249937f4a5dff9ed1abb03f5c20d9dd88659d

test:
  secret_key_base: 2a02894b489be3104ffdf8d3746a8f027182842d747989f26cf85325b11b1f6cce219a9c837c8d855f8678ec7c6f8151cb3a73addf6a8fe7b478852e0e1459f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
