require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe OrderSlipsController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # OrderSlip. As you add validations to OrderSlip, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrderSlipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all order_slips as @order_slips" do
      order_slip = OrderSlip.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:order_slips)).to eq([order_slip])
    end
  end

  describe "GET show" do
    it "assigns the requested order_slip as @order_slip" do
      order_slip = OrderSlip.create! valid_attributes
      get :show, {:id => order_slip.to_param}, valid_session
      expect(assigns(:order_slip)).to eq(order_slip)
    end
  end

  describe "GET new" do
    it "assigns a new order_slip as @order_slip" do
      get :new, {}, valid_session
      expect(assigns(:order_slip)).to be_a_new(OrderSlip)
    end
  end

  describe "GET edit" do
    it "assigns the requested order_slip as @order_slip" do
      order_slip = OrderSlip.create! valid_attributes
      get :edit, {:id => order_slip.to_param}, valid_session
      expect(assigns(:order_slip)).to eq(order_slip)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OrderSlip" do
        expect {
          post :create, {:order_slip => valid_attributes}, valid_session
        }.to change(OrderSlip, :count).by(1)
      end

      it "assigns a newly created order_slip as @order_slip" do
        post :create, {:order_slip => valid_attributes}, valid_session
        expect(assigns(:order_slip)).to be_a(OrderSlip)
        expect(assigns(:order_slip)).to be_persisted
      end

      it "redirects to the created order_slip" do
        post :create, {:order_slip => valid_attributes}, valid_session
        expect(response).to redirect_to(OrderSlip.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved order_slip as @order_slip" do
        post :create, {:order_slip => invalid_attributes}, valid_session
        expect(assigns(:order_slip)).to be_a_new(OrderSlip)
      end

      it "re-renders the 'new' template" do
        post :create, {:order_slip => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested order_slip" do
        order_slip = OrderSlip.create! valid_attributes
        put :update, {:id => order_slip.to_param, :order_slip => new_attributes}, valid_session
        order_slip.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested order_slip as @order_slip" do
        order_slip = OrderSlip.create! valid_attributes
        put :update, {:id => order_slip.to_param, :order_slip => valid_attributes}, valid_session
        expect(assigns(:order_slip)).to eq(order_slip)
      end

      it "redirects to the order_slip" do
        order_slip = OrderSlip.create! valid_attributes
        put :update, {:id => order_slip.to_param, :order_slip => valid_attributes}, valid_session
        expect(response).to redirect_to(order_slip)
      end
    end

    describe "with invalid params" do
      it "assigns the order_slip as @order_slip" do
        order_slip = OrderSlip.create! valid_attributes
        put :update, {:id => order_slip.to_param, :order_slip => invalid_attributes}, valid_session
        expect(assigns(:order_slip)).to eq(order_slip)
      end

      it "re-renders the 'edit' template" do
        order_slip = OrderSlip.create! valid_attributes
        put :update, {:id => order_slip.to_param, :order_slip => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested order_slip" do
      order_slip = OrderSlip.create! valid_attributes
      expect {
        delete :destroy, {:id => order_slip.to_param}, valid_session
      }.to change(OrderSlip, :count).by(-1)
    end

    it "redirects to the order_slips list" do
      order_slip = OrderSlip.create! valid_attributes
      delete :destroy, {:id => order_slip.to_param}, valid_session
      expect(response).to redirect_to(order_slips_url)
    end
  end

end
